export const optionsLanguages = [
  { value: 'markup', label: 'markup' },
  { value: 'css', label: 'css' },
  { value: 'clike', label: 'clike' },
  { value: 'javascript', label: 'javascript' },
  { value: 'actionscript', label: 'actionscript' },
  { value: 'aspnet', label: 'aspnet' },
  { value: 'bash', label: 'bash' },
  { value: 'c', label: 'c' },
  { value: 'csharp', label: 'csharp' },
  { value: 'docker', label: 'docker' },
  { value: 'go', label: 'go' },
  { value: 'graphql', label: 'graphql' },
  { value: 'http', label: 'http' },
  { value: 'java', label: 'java' },
  { value: 'json', label: 'json' },
  { value: 'json5', label: 'json5' },
  { value: 'jsonp', label: 'jsonp' },
  { value: 'kotlin', label: 'kotlin' },
  { value: 'makefile', label: 'makefile' },
  { value: 'markdown', label: 'markdown' },
  { value: 'markup-templating', label: 'markup-templating' },
  { value: 'mongodb', label: 'mongodb' },
  { value: 'nginx', label: 'nginx' },
  { value: 'ocaml', label: 'ocaml' },
  { value: 'php', label: 'php' },
  { value: 'python', label: 'python' },
  { value: 'jsx', label: 'jsx' },
  { value: 'tsx', label: 'tsx' },
  { value: 'ruby', label: 'ruby' },
  { value: 'rust', label: 'rust' },
  { value: 'scss', label: 'scss' },
  { value: 'smarty', label: 'smarty' },
  { value: 'sql', label: 'sql' },
  { value: 'swift', label: 'swift' },
  { value: 'toml', label: 'toml' },
  { value: 'twig', label: 'twig' },
  { value: 'typescript', label: 'typescript' },
  { value: 'vim', label: 'vim' },
  { value: 'warpscript', label: 'warpscript' },
  { value: 'wasm', label: 'wasm' },
  { value: 'yaml', label: 'yaml' },
]

export default optionsLanguages
